---
- name : install Apache2 on debian
  hosts: linux_servers
  become: true
  tasks: 

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Start install
      apt: "pkg=apache2 state=installed update_cache=true"
        